import { basename } from 'node:path';
import type { ReviewResult, Severity, Usage } from '../providers/types.js';
import { estimateCost, formatTokens, formatUsd } from './pricing.js';

export interface MarkdownArgs {
  filePath: string;
  model: string;
  verifierModel?: string;
  result: ReviewResult;
  elapsedMs?: number;
  usage?: Usage;
}

function locSnippet(file: string, startLine: number, endLine?: number): string {
  const range = endLine && endLine !== startLine ? `${startLine}-${endLine}` : `${startLine}`;
  return `\`${file}:${range}\``;
}

function summaryLine(args: MarkdownArgs): string {
  const parts: string[] = [];
  if (args.verifierModel) parts.push(`${args.model} → ${args.verifierModel}`);
  else parts.push(args.model);
  if (args.elapsedMs !== undefined) parts.push(`${(args.elapsedMs / 1000).toFixed(1)}s`);
  if (args.usage) {
    const cached = args.usage.cachedInputTokens ?? 0;
    const tokens = `${formatTokens(args.usage.inputTokens)} in${cached > 0 ? ` (${formatTokens(cached)} cached)` : ''} / ${formatTokens(args.usage.outputTokens)} out`;
    parts.push(tokens);
    const cost = estimateCost(args.verifierModel ?? args.model, args.usage);
    if (cost !== null) parts.push(`~${formatUsd(cost)}`);
  }
  return parts.join(' · ');
}

export function toMarkdown(args: MarkdownArgs): string {
  const file = basename(args.filePath);
  const counts: Record<Severity, number> = {
    critical: args.result.findings.filter(f => f.severity === 'critical').length,
    medium:   args.result.findings.filter(f => f.severity === 'medium').length,
    low:      args.result.findings.filter(f => f.severity === 'low').length
  };

  const lines: string[] = [];
  lines.push(`### Review: \`${file}\``);
  lines.push('');
  lines.push(`_${summaryLine(args)}_`);
  lines.push('');
  lines.push(`**${counts.critical} critical · ${counts.medium} medium · ${counts.low} low**`);
  lines.push('');
  lines.push(args.result.summary);

  const ORDER: Severity[] = ['critical', 'medium', 'low'];
  const LABELS: Record<Severity, string> = { critical: 'Critical', medium: 'Medium', low: 'Low' };

  for (const sev of ORDER) {
    const bucket = args.result.findings.filter(f => f.severity === sev);
    if (bucket.length === 0) continue;
    lines.push('');
    lines.push(`#### ${LABELS[sev]} (${bucket.length})`);
    for (const f of bucket) {
      const loc = f.location ? ' ' + locSnippet(file, f.location.startLine, f.location.endLine) : '';
      const cat = f.category ? ` _(${f.category})_` : '';
      lines.push('');
      lines.push(`- **${f.title}**${loc}${cat}`);
      lines.push(`  ${f.explanation.split('\n').join(' ')}`);
      if (f.snippet) {
        lines.push('  ```');
        for (const l of f.snippet.split('\n')) lines.push('  ' + l);
        lines.push('  ```');
      }
      if (f.fix) lines.push(`  **Fix:** ${f.fix}`);
    }
  }
  if (args.result.notes) {
    lines.push('');
    lines.push(`_${args.result.notes}_`);
  }

  lines.push('');
  lines.push(`<sub>Generated by <a href="https://github.com/dcccrypto/isolated-review">isolated-review</a></sub>`);
  return lines.join('\n') + '\n';
}
